<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="laptopcuatruong" failures="1" tests="4" name="TESTCASES.Test_Delete_Category2" time="24.054" errors="0" timestamp="2023-11-08T03:36:45 ICT" skipped="0">
  <testcase classname="TESTCASES.Test_Delete_Category2" name="TC02_test_Delete_Category" time="6.747">
    <failure message="Lỗi do  expected [Xóachuyênmụckhôngthànhcông,có1bàiviếtđượcliênkết.] but found [Cácchuyênmụcđãbịxóa.Bỏquathôngbáonày]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Lỗi do  expected [Xóachuyênmụckhôngthànhcông,có1bàiviếtđượcliênkết.] but found [Cácchuyênmụcđãbịxóa.Bỏquathôngbáonày]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at PAGES.delete_category_page.check_Delete_category(delete_category_page.java:81)
at PAGES.delete_category_page.Delete_category(delete_category_page.java:21)
at TESTCASES.Test_Delete_Category2.TC02_test_Delete_Category(Test_Delete_Category2.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC02_test_Delete_Category -->
  <system-out/>
  <testcase classname="TESTCASES.Test_Delete_Category2" name="TC04_test_Delete_Category" time="3.359"/>
  <system-out/>
  <testcase classname="TESTCASES.Test_Delete_Category2" name="TC03_test_Delete_Category" time="5.465"/>
  <system-out/>
  <testcase classname="TESTCASES.Test_Delete_Category2" name="TC01_test_Delete_Category" time="8.483"/>
  <system-out/>
</testsuite> <!-- TESTCASES.Test_Delete_Category2 -->
